version: '3.8'

services:
    db:
      image: postgres:16.1-alpine
      container_name: qrcodedb
      restart: always
      volumes:
        - ./templates/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      environment:
        POSTGRES_USER: ${POSTGRESDB_USER}
        POSTGRES_PASSWORD: ${POSTGRESDB_PASSWORD}
        POSTGRES_DB: ${POSTGRESDB_DATABASE}
      ports:
        - ${POSTGRESDB_PORT}:${POSTGRESDB_PORT}
      env_file:
        - local.env
