version: '3.8'

services:
    db:
      image: postgres:16.1
      container_name: qrcodedb
      restart: always
      volumes:
        - ./templates/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      environment:
        POSTGRES_DB: $${database.name}
        POSTGRES_USER: $${database.username}
        POSTGRES_PASSWORD: $${database.password}
      ports:
        - '5432:5432'
      env_file:
        - local.yml
